name: SNS Auto Post

on:
  schedule:
    # 毎日17:00（日本時間）に実行
    - cron: '0 8 * * *'  # UTC時間で設定
  workflow_dispatch: # 手動実行も可能

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install tweepy==4.14.0 google-api-python-client==2.86.0 google-auth==2.17.3
    
    - name: Run posting script
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        GOOGLE_SHEETS_ID: '1YKHCDU7NswNo5p3UHy6Q5jdTtChoCAXo4B_KTmGjlsI'
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python scripts/auto_post_v2.py